class TwitterAds::Stats::Account
  def to_pb(account_id : String)
    TwitterAds::Proto::Stats::Account.new(
      account_id: account_id,
      entity: entity,
      entity_ids: entity_ids,
      start_time: start_time,
      end_time: end_time,
      metric_groups: metric_groups,
      granularity: granularity,
      placement: placement,
      segmentation_type: segmentation_type,
      country: country,
      platform: platform,
      engagements: engagements,
      impressions: impressions,
      retweets: retweets,
      replies: replies,
      likes: likes,
      follows: follows,
      card_engagements: card_engagements,
      clicks: clicks,
      app_clicks: app_clicks,
      url_clicks: url_clicks,
      qualified_impressions: qualified_impressions,
      billed_engagements: billed_engagements,
      billed_charge_local_micro: billed_charge_local_micro,
      video_total_views: video_total_views,
      video_views_25: video_views_25,
      video_views_50: video_views_50,
      video_views_75: video_views_75,
      video_views_100: video_views_100,
      video_cta_clicks: video_cta_clicks,
      video_content_starts: video_content_starts,
      video_mrc_views: video_mrc_views,
      video_3s100pct_views: video_3s100pct_views,
      media_views: media_views,
      media_engagements: media_engagements,
    )
  end
end
